protected/models/Orders.php
<?php

/**
 * This is the model class for table "orders".
 *
 * The followings are the available columns in table 'orders':
 * @property integer $cam_id
 * @property integer $user_id
 * @property integer $price
 * @property string $date
 *
 * The followings are the available model relations:
 * @property Camerists $cam
 * @property Users $user
 */
class Orders extends CActiveRecord
{


    // For date convert
    protected function beforeSave() {
        if(parent::beforeSave()) {
            $this->date = date('Y-m-d H:i:s', strtotime($this->date));
            return true;
        } else {
            return false;
        }
    }




	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'orders';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('cam_id, user_id, price, date', 'required'),
			array('cam_id, user_id, price', 'numerical', 'integerOnly'=>true),
            array('price', 'in', 'range'=>range(10,1000), 'message' => 'Как минимум 10 долларов, но не больше 1000'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('cam_id, user_id, price, date', 'safe', 'on'=>'search'),
            array('date', 'ext.validators.busyDay', 'on'=>'insert'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'cam' => array(self::BELONGS_TO, 'Camerists', 'cam_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'cam_id' => 'Cam',
			'user_id' => 'User',
			'price' => 'Price',
			'date' => 'Date',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('cam_id',$this->cam_id);
		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('price',$this->price);
		$criteria->compare('date',$this->date,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    // Get all active orders
    public function getBusy($cam)
    {
        $criteria = new CDbCriteria();

        $criteria->condition = 'cam_id = :id AND status = "In progress"';

        $criteria->params = array(':id'=>$cam);

        return Orders::model()->findAll($criteria);

    }


    public function findOrders($cam)
    {
        $criteria = new CDbCriteria();
        $criteria->condition = 'cam_id = :id AND status != :status';
        $criteria->params = array(':id'=>$cam, ':status' => 'closed');

        return Orders::model()->findAll($criteria);
    }

    public function acceptOrder()
    {

    }
	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Orders the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

    public function setAccept($accept = true)
    {
        $this->accepted = $accept; // True or false, look in controller's methods
    }


}

protected/controllers/OrdersController.php
<?php

class OrdersController extends Controller
{

    public function filters()
    {
        return array(
            'accessControl'
        );
    }



    public function accessRules()
    {
        return array(
            array('deny',
                'actions'=>array('accept', 'decline', 'finish', 'make'), // Guests can't rule the orders
                'users'=>array('?'),
            ),
            array('deny',
                'actions'=>array('make'),
                'roles'=>array('camerist'),
            ),
            array('allow',
                'actions'=>array('index', 'close'),
                'roles'=>array('user'),
            ),

        );
    }


	public function actionIndex()
	{

        // for pagination

        $criteria = new CDbCriteria();
        $criteria->condition = 'user_id = :u_id';
        $criteria->order = 'id desc';
        $criteria->params = array(':u_id' => Yii::app()->user->id);
        $count = Orders::model()->count($criteria);
        $pages = new CPagination($count);

        $pages->pageSize = 10; // 10 orders per page
        $pages->applyLimit($criteria);

        $myOrders = Orders::model()->findAll($criteria); //Orders::model()->findAllByAttributes(array('user_id' => Yii::app()->user->id));
		$camerists = array();
        foreach($myOrders as $o)
            $camerists[] = Users::model()->findByPk($o->cam_id);
        $this->render('index', array('orders' => $myOrders, 'camerists' => $camerists, 'pages' => $pages));
	}




    // TODO: bullshit, needs to refactor
    public function actionAccept()
    {

        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->accepted = true;
        $order->status = 'In progress';
        $order->save();
        $this->redirect('../cabinet/member/job');
    }

    public function actionDecline()
    {
        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->accepted = false;
        $order->status = 'Refused';

        $order->save();
        $this->redirect('../cabinet/member/job');
    }

    public function actionFinish()
    {
        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->status = 'Finished';

        $order->save();
        $this->redirect('../cabinet/member/job');
    }

    public function actionClose()
    {
        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->status = 'Closed';

        $order->save();
        $this->redirect('../orders/index');
    }


    public function actionMake()
    {
        $camId = Yii::app()->request->getQuery('cam_id');

        $orders = new Orders;
        $busy = Orders::model()->getBusy($camId);
        if(isset($_POST['Orders']))
        {
            $orders->attributes = $_POST['Orders'];
            $orders->cam_id = $camId;
            $orders->user_id = Yii::app()->user->id;

            if($orders->save())
                $this->render('congrats');
            else
                $this->render('make', array('model' => $orders, 'busy' => $busy));
        }
        else
            $this->render('make', array('model' => $orders, 'busy' => $busy));
    }

}

protected/views/orders/congrats.php
<h1>Congrats!</h1>

<p>Your order successfully added.</p>

protected/views/orders/index.php
<?php
/* @var $this OrdersController */

$this->breadcrumbs=array(
	'Orders',
);
?>
<h1>My orders</h1>
<?php if(!$orders)
    echo 'No orders yet';
?>
<?php foreach($orders as $i => $o): ?>
        <div class="order">
        <?php
            if(isset($camerists[$i]))
            {
                echo 'Photographer: ' . CHtml::link($camerists[$i]->login, '../camerists/info?cam_id=' .$camerists[$i]->id ). '<br />';
                echo 'Date: ' . date('d/m/Y',strtotime($o->date)) . '<br />';
                echo 'Status: '.$o->status . '<br />';
                echo 'Payment: '. $o->price . '$<br />';
                if(($o->status != 'Refused') && ($o->status != 'Closed'))
                    echo CHtml::link('Close order', Yii::app()->createUrl('orders/close', array('order' => $o->id)));

            }
        ?>
        </div>
<?php endforeach; ?>

<?php
    $this->widget('CLinkPager', array(
        'pages' => $pages,
    ));
?>

protected/views/orders/make.php
<div class="form">
    <?php echo CHtml::beginForm(); ?>

    <?php echo CHtml::activeLabel($model, 'Photographer schedule'); ?>
    <hr />

    <?php echo CHtml::errorSummary($model); ?>


    <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
        'name' => 'date',
        'model' => $model,
        'attribute' => 'date',
        'language' => 'en',
        'flat' => true,
        'value' => date('d/m/Y'),
    ));?>

    <div class="row">
        <?php echo CHtml::activeLabel($model, 'price($)'); ?>
        <?php echo CHtml::activeTextField($model, 'price'); ?>
    </div>
    Busy days:
    <br />
    <div class="row">
        <?php
            foreach($busy as $b)
            {
                echo date('d/m/Y',strtotime($b->date));
            }
        ?>
    </div>

    <div class="row submit">
        <?php echo CHtml::submitButton('Order'); ?>
    </div>

    <?php echo CHtml::endForm(); ?>
</div><!-- form -->