protected/controllers/CameristsController.php
<?php

class CameristsController extends Controller
{

    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    // List of all masters
	public function actionIndex()
	{
        // for pagination

        $criteria = new CDbCriteria();
        $criteria->condition = 'role = :role';
        $criteria->params = array(':role' => 'camerist');
        $count = Users::model()->count($criteria);
        $pages = new CPagination($count);
        $pages->pageSize = 15; // 15 per page
        $pages->applyLimit($criteria);

        $criteria->with = array('camerists');
        $criteria->together = true;




        $allCamerists = Users::model()->findAll($criteria);
        $this->render('index', array('camerists' => $allCamerists, 'pages' => $pages));
	}


    public function actionInfo(){




        $id = Yii::app()->request->getQuery('cam_id');
        $usr = Users::model()->findByPk($id);

        // For ghosts
        if(!isset($usr)){
            throw new CHttpException(404,'The specified post cannot be found.');
        }
        if($usr->role == 'user')
        {
            throw new CHttpException(404,'The specified post cannot be found.');
        }
        // Rate him

        $rating = new Rating;
        $cam = Camerists::model()->findByPk($id); // Save camerist for order
        if(isset($_POST['Rating'])){
            $rating->attributes = Yii::app()->request->getPost('Rating');
            $rating->cam_id = $id;
            $rating->user_id = Yii::app()->user->id;
            if($rating->save())
            {
                $cam->updateRating();
            }
        }


        $rate = $cam->rate;
        $album = Albums::model()->getAlbumId($id);
        $reviews = Comments::model()->getComments($id);
        $commenters = array();

        foreach($reviews as $rv)
            $commenters[] = Users::model()->findByPk($rv->user_id);
        $this->render('info', array(
            'camerist' => $usr,
            'commenters' => $commenters,
            'rate' => $rate,
            'album' => $album->getPhotos(),
            'reviews' => $reviews,
            'model' => $rating,  // for rate him at info page
        ));
    }
}

protected/controllers/CommentsController.php
<?php

class CommentsController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl'
        );
    }


    public function accessRules()
    {
        return array(
            array('deny',
                'actions'=>array('add'),
                'users'=>array('?'),
            ),
            array('deny',
                'actions'=>array('add'),
                'roles'=>array('camerist'),
            ),
            array('allow',
                'actions'=>array('add', 'remove'),
                'roles'=>array('user'),
            ),

        );
    }


    public function actionRemove()
    {
        Comments::model()->remove($_GET['comm']);
        $this->redirect('index');
    }

	public function actionIndex()
	{
        $reviews = Comments::model()->findAllByAttributes(array('user_id' => Yii::app()->user->id));
        $camerists = array();
        // Just simple getting aims of comments
        foreach($reviews as $r)
            $camerists[] = Users::model()->findByPk($r->cam_id);

        $this->render('index', array('reviews' => $reviews, 'camerists' => $camerists));
	}

    public function actionAdd()
    {
        $comm = new Comments;

        // Leave comment

        if(isset($_POST['Comments']))
        {
            $comm->user_id = Yii::app()->user->id;
            $comm->cam_id = $_GET['cam_id'];
            $comm->attributes = Yii::app()->request->getPost('Comments');//$_POST['Comments'];
            if($comm->save())
                $this->render('congrats');
            else
                $this->render('add', array('model' => $comm));
        }
        else
        $this->render('add', array('model' => $comm));
    }


}

protected/controllers/RatingController.php
<?php

class RatingController extends Controller
{

    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array('deny',
                'actions'=>array('rate'),
                'users'=>array('?'),
            ),
            array('allow',
                'actions'=>array('rate', 'change'),
                'roles'=>array('user'),
            ),
            array('deny',
                'actions'=>array('rate'),
                'roles'=>array('camerist'),
            ),
        );
    }


    public function actionChange()
    {

        $criteria = new CDbCriteria;
        $criteria->select = 'id';
        $criteria->condition = 'cam_id = :c_id AND user_id = :u_id';
        $criteria->params = array(':c_id' => Yii::app()->request->getQuery('cam_id'), ':u_id'=>Yii::app()->user->id);
        Rating::model()->find($criteria)->delete();
        //Rating::model()->delete();
        $camId = Yii::app()->request->getQuery('cam_id');
        $cam = Camerists::model()->findByPk($camId); // Save camerist for order
        $cam->updateRating();
        $this->redirect(array('camerists/info', 'cam_id' => $camId));
    }


    public function actionIndex()
    {

        $rates = Rating::model()->findAllByAttributes(array('user_id' => Yii::app()->user->id));
        $camerists = array();
        // Just simple getting aims of comments
        foreach($rates as $r)
            $camerists[] = Users::model()->findByPk($r->cam_id);

        $this->render('index', array('rates' => $rates, 'camerists' => $camerists));
    }

    public function actionRate()
    {
        $rating = new Rating;

        $camId = Yii::app()->request->getQuery('cam_id');
        $cam = Camerists::model()->findByPk($camId); // Save camerist for order
        if(isset($_POST['Rating'])){
            $rating->attributes = Yii::app()->request->getPost('Rating');
            $rating->cam_id = $camId;
            $rating->user_id = Yii::app()->user->id;
            if($rating->save())
            {
                $this->render('congrats');
                $cam->updateRating();
            }
            else
                $this->render('rate', array('model'=>$rating));
        }
        else
            $this->render('rate', array('model'=>$rating));
    }

}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */
$baseUrl = Yii::app()->request->baseurl;
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />

    <!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/screen.css" media="screen, projection" />
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/print.css" media="print" />
    <!--[if lt IE 8]>
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/ie.css" media="screen, projection" />
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/jquery.bxslider.css" />

    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/form.css" />
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans|Open+Sans:300&subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/juicyslider.css" />
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/south-street/jquery-ui.css" id="theme">
    <link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $baseUrl; ?>/css/style000.css" />

    <title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <!--скрипты-->


    <script src="//yandex.st/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <script src="<?php echo $baseUrl; ?>/js/yandexmap.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="http://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
    <script src="<?php echo $baseUrl; ?>/js/jquery.image-gallery.min.js"></script>



</head>

<body>
<div id="page">
    <div class="container">
        <div class="row head_background ">

            <div id="header" class="col-lg-3">
                <a href="<?php echo $baseUrl; ?>">
                    <div id="logo"><img src="<?php echo $baseUrl; ?>/css/logo1.png" width="300px"></div>
                </a>
            </div><!-- header -->

            <div id="mainmenu" class="pull-right">
                <?php

                $this->widget('zii.widgets.CMenu',array(
                    'items'=>array(
                        array('label'=>'Главная', 'url'=>array('/site/index')),
                        array('label'=>'Фотографы', 'url'=>array('/camerists/index')),
                        array('label'=>'Регистрация', 'url'=>array('/cabinet/auth/registration'), 'visible'=>Yii::app()->user->isGuest),
                        array('label'=>'Войти', 'url'=>array('/cabinet/auth/login'), 'visible'=>Yii::app()->user->isGuest),
                        array('label'=>'Мой кабинет', 'url'=>array("/camerists/info?cam_id=".Yii::app()->user->id ),
                            'visible'=>Yii::app()->user->isCamerist(), 'items'=>array(
                            array('label'=>'Информация', 'url'=>array('/cabinet/member/dashboard')),
                            array('label'=>'Настройки', 'url'=>array('/cabinet/member/account')),
                            array('label'=>'Добавить фотографии', 'url'=>array('/cabinet/photos/create')),
                            array('label'=>'Заказы', 'url'=>array('/cabinet/member/job')),
                            array('label'=>'Добавить место', 'url' => array('/map/newPlacemark'))
                        ),

                        ),
                        array('label'=>'Мои', 'url'=>array(''),
                            'visible'=>Yii::app()->user->isUser(), 'items'=>array(
                            array('label'=>'Заказы', 'url'=>array('/orders/index')),
                            array('label'=>'Отзывы', 'url'=>array('/comments/index')),
                            array('label'=>'Оценки', 'url'=>array('/rating/index')),
                        )),
                        array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest),
                    ),
                ));
                ?>

            </div><!-- mainmenu -->
        </div>


<!--        <div id="usermenu">-->
<!--            --><?php
//            $this->widget('zii.widgets.CMenu',array(
//                'items'=>array(
//                    array('label'=>'My orders', 'url'=>array('/orders/index'), 'visible'=>Yii::app()->user->isUser()),
//                    array('label'=>'My reviews', 'url'=>array('/comments/index'), 'visible'=>Yii::app()->user->isUser()),
//                    array('label'=>'My rates', 'url'=>array('/rating/index'), 'visible'=>Yii::app()->user->isUser()),
//                ),
//            ));
//            ?>
<!--        </div>-->


        <?php echo $content; ?>


        <div class="clear"></div>

    </div>
    <div class="space"></div>
</div><!-- page -->

<!--Start footer-->

<footer>
    <div><p class="text-center">© 2014 FreeLens.us. All rights reserved.</p></div>
</footer>

<!--End footer-->

</body>
</html>

protected/views/layouts/main2.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/style000.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>

    <!--скрипты-->
    <script src="//yandex.st/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/yandexmap.js"></script>
</head>

<body>




<div class="container" id="page">

	<div id="header">
		<div id="logo"><img src="<?php echo Yii::app()->request->baseUrl; ?>/css/logo1.png" width="300px"></div>
	</div><!-- header -->

	<div id="mainmenu">




    <?php

        $this->widget('zii.widgets.CMenu',array(
            'items'=>array(
                array('label'=>'Home', 'url'=>array('/site/index')),
                array('label'=>'Photographers', 'url'=>array('/camerists/index')),
                array('label'=>'Sign up', 'url'=>array('/cabinet/auth/registration'), 'visible'=>Yii::app()->user->isGuest),
                array('label'=>'Sign in', 'url'=>array('/cabinet/auth/login'), 'visible'=>Yii::app()->user->isGuest),
                array('label'=>'Cabinet', 'url'=>array('/cabinet/member/dashboard'), 'visible'=>Yii::app()->user->isCamerist(), 'items'=>array(
                    array('label'=>'Dashboard', 'url'=>array('/cabinet/member/dashboard')),
                    array('label'=>'Settings', 'url'=>array('/cabinet/member/account')),
                    array('label'=>'Add photo', 'url'=>array('/cabinet/photos/create')),
                    array('label'=>'Job', 'url'=>array('/cabinet/member/job')),
                )),
                array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest),
            ),
        ));
    ?>

	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>
    <div id="usermenu">
        <?php
        $this->widget('zii.widgets.CMenu',array(
            'items'=>array(
                array('label'=>'My orders', 'url'=>array('/orders/index'), 'visible'=>Yii::app()->user->isUser()),
                array('label'=>'My reviews', 'url'=>array('/comments/index'), 'visible'=>Yii::app()->user->isUser()),
                array('label'=>'My rates', 'url'=>array('/rating/index'), 'visible'=>Yii::app()->user->isUser()),
            ),
        ));
        ?>
    </div>

<!--    <div id="cabmenu">-->
<!--        --><?php //if(Yii::app()->user->getRole() == 'camerist'){ ?>
<!--            --><?php //$this->widget('zii.widgets.CMenu',array(
//                'items'=>array(
//                    array('label'=>'Dashboard', 'url'=>array('/cabinet/member/dashboard')),
//                    array('label'=>'Settings', 'url'=>array('/cabinet/member/account')),
//                    array('label'=>'Add photo', 'url'=>array('/cabinet/photos/create')),
//                    array('label'=>'Job', 'url'=>array('/cabinet/member/job')),
//
//                ),
//            ));
//        }
//        ?>
<!--    </div>-->
	<?php echo $content; ?>

	<div class="clear"></div>

</div><!-- page -->

<div id="footer">
    <div class="foot">
        <ul>
            <li><a href="#">О сайте</a></li>
            <li><a href="#">Найти фотографа</a></li>
            <li><a href="#">Карта сайта</a></li>
            <li><a href="#">Фидбек</a></li>
        </ul>
    </div>
</div><!-- footer -->

</body>
</html>