protected/models/Map.php
<?php

/**
 * This is the model class for table "map".
 *
 * The followings are the available columns in table 'map':
 * @property integer $id
 * @property string $stylePlacemark
 * @property string $balloonText
 * @property string $lat
 * @property string $lon
 */
class Map extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'map';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('lat, lon', 'required'),
			array('stylePlacemark, balloonText, lat, lon', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, stylePlacemark, balloonText, lat, lon', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'stylePlacemark' => 'Style Placemark',
			'balloonText' => 'Balloon Text',
			'lat' => 'Lat',
			'lon' => 'Lon',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('stylePlacemark',$this->stylePlacemark,true);
		$criteria->compare('balloonText',$this->balloonText,true);
		$criteria->compare('lat',$this->lat,true);
		$criteria->compare('lon',$this->lon,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Map the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/MapController.php
<?php

class MapController extends Controller
{


    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function actionIndex()
    {
        $this->render('index');
    }

    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('newPlacemark', 'upload'),
                'roles'=>array('camerist'),
            ),
            array('allow',
                'actions'=>array('showPlaces'),
                'users'=>array('*'),
            ),
            array('deny',
                'actions'=>array('newPlacemark', 'upload'),
                'users'=>array('*'),
            ),
        );
    }


    /*
     * Страница добавления новой места на карте.
     * TODO: сделать разрешение доступа только для фотографов
     */
    public function actionNewPlacemark()
    {
        $album = Albums::model()->getAlbumId(Yii::app()->user->id);
        $id = Yii::app()->user->id;
        $this->render('newPlacemark', array('id' => $id, 'album' => $album->getPhotos()));
    }




    // Uploader
    public function actionUpload()
    {
        Yii::import("ext.EAjaxUpload.qqFileUploader");

        $folder='images/';// folder for uploaded files
        $allowedExtensions = array('jpg', 'png');//array("jpg","jpeg","gif","exe","mov" and etc...
        $sizeLimit = 15 * 1024 * 1024;// maximum file size in bytes
        $uploader = new qqFileUploader($allowedExtensions, $sizeLimit);
        $result = $uploader->handleUpload($folder);

        $return = htmlspecialchars(json_encode($result), ENT_NOQUOTES);

        //$fileId=$result['id'];//Here file id

        echo $return; // it's array
    }



    /*
     * страница вывода меток опрееленного фотографа
     */
    public function actionShowPlaces() {

        $this->render('showPlaces');
    }

    public function actionGetCamPhotos(){
        header('Content-Type: text/html; charset=utf-8');
        $connect = Yii::app()->db;
        $id = $_GET['id'];


        $sql = "select * from photos where id in(
            select photo_id from placemark_photos WHERE placemark_id = $id )";

        $result = $connect->createCommand($sql)->query();

        if($result){
            //all photo data in JSON
            foreach($result as $value){
                $json = array(
                    'id' => $value['id'],
                    'small_path' => Thumbnail::getThumb($value['path']),
                    'path' => $value['path'],
                    'desc' => $value['desc']
                );

                $photo[] = $json;
            }

        }

        $photos = array('photo' => $photo);
        echo json_encode($photos);
    }


    /*
     * Отдает на выход массив маркеров в JSON формате
     */
    public function actionGetMap(){
        header('Content-Type: text/html; charset=utf-8');
        $connect = Yii::app()->db;

        //если id пользователя передан, ищем по нему,
        //иначе выбираем все записи
        $id = Yii::app()->request->getQuery('id');
        if(isset($id)){
            $result = $connect->createCommand()
                ->select('*')
                ->from('map')
                ->where('cam_id=:id', array(':id'=>$id))
                ->query();
        }
        else{
            $result = $connect->createCommand()
                ->select('*')
                ->from('map')
                ->query();
        }

        if($result){
            //all placemarks data in JSON
            foreach($result as $value){
                $json = array(
                    'idPlace' => $value['id'],
                    'name' => $value['name'],
                    'stylePlacemark' => $value['stylePlacemark'],
                    'balloonText' => $value['balloonText'],
                    'lat' => $value['lat'],
                    'lon' => $value['lon']
                );

                $markers[] = $json;
            }
        }

        $points = array('markers' => $markers);
        echo json_encode($points);
    }


    /*
     * Звнесение новой метки в БД
     */
    public function actionAddToMap(){
        //TODO: создать транзакцию, написать подготавливаемые запросы

        header('Content-Type: text/html; charset=utf-8');
        $connect = Yii::app()->db;

        $cam_id = htmlspecialchars($_POST['cam_id']);
        $name = htmlspecialchars($_POST['name']);
        $balloonText = htmlspecialchars($_POST['balloonText']);
        $lat = $_POST['lat'];
        $lon = $_POST['lon'];

        $connect->createCommand()->insert('map', array(
            'cam_id' => $cam_id,
            'name' => $name,
            'balloonText' => $balloonText,
            'lat' => $lat,
            'lon' => $lon
        ));

        $place_id = $connect->getLastInsertID();
        $photo_ids = json_decode($_POST['photo_ids']);

        foreach($photo_ids as $value){
            $connect->createCommand()->insert('placemark_photos', array(
                'placemark_id' => $place_id,
                'photo_id' => $value
            ));
        }
    }


    /*
     * Возвращает JSON-массив юзеров, если вызвать action без параметров
     * если передать id, то возвращает массив с одним фотографом
     */
    public function actionGetCamLocation(){

        header('Content-Type: text/html; charset=utf-8');
        $connect = Yii::app()->db;
        if(isset($_GET['id'])){
            $result = $connect->createCommand()
                ->select('*')
                ->from('users')
                ->where('id=:id', array(':id'=>$_GET['id']))
                ->queryAll();

        }
        else{
            $result = $connect->createCommand()
                ->select('*')
                ->from('users')
                ->where('role="camerist"')
                ->queryAll();
        }

        if($result){
            //lat and lon in JSON array
            foreach($result as $value){
                $json = array(
                    'lat' => $value['lat'],
                    'lon' => $value['lon'],
                    'fio' => $value['fio'],
                    'id' => Yii::app()->urlManager->createUrl("/camerists/info", array('cam_id'=>$value['id'])),
                    'avatar' => Yii::app()->request->baseUrl.'/'.$value['avatar']
                );
                $marker[] = $json;
            }
        }

        $location = array('marker' => $marker);
        echo json_encode($location);

    }



    // Uncomment the following methods and override them if needed
    /*
    public function filters()
    {
        // return the filter configuration for this controller, e.g.:
        return array(
            'inlineFilterName',
            array(
                'class'=>'path.to.FilterClass',
                'propertyName'=>'propertyValue',
            ),
        );
    }

    public function actions()
    {
        // return external action classes, e.g.:
        return array(
            'action1'=>'path.to.ActionClass',
            'action2'=>array(
                'class'=>'path.to.AnotherActionClass',
                'propertyName'=>'propertyValue',
            ),
        );
    }
    */
}

protected/views/map/index.php
<?php
/* @var $this MapController */

$this->breadcrumbs=array(
	'Map',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

protected/views/map/newPlacemark.php
<?php
/* @var $this SiteController */
$this->pageTitle=Yii::app()->name;
?>


<div class="row">
    <h2 class="page-header">Добавление метки на карту</h2>
    <p>Выберите место на карте. Заполните форму. Сохраните. Радуйтесь.</p>
    <div class="col-lg-8"><h3 class="page-header">1. Выберите место</h3>
        <div id="map" class="map"></div>
        <div class="col-md-offset-10">
            <button id="change_id" class="btn btn-success">Показать все метки</button>
        </div>

    </div> <!--Блок с картой-->

    <div class="col-lg-4">
        <h3 class="page-header">2. Заполните информацию</h3>
        <!-- CONTACT FORM -->
        <form id="marker_form">
            <div id="add_marker">
                <div class="form-group">
                    <label for="marker_name">Название места</label><input class="form-control" type="text" name="marker_name" id="marker_name">
                </div>
                <div class="form-group">
                    <label for="balloon_text">Описание</label><textarea class="form-control" name="balloon_text" id="marker_balloontext" rows="5" cols="25"></textarea><br>
                </div>
                <div class="form-group">
                    <label for="lat">Широта</label><input class="form-control" type="text" name="lat" id="marker_lat" value="" disabled><br>
                </div>
                <div class="form-group">
                    <label for="lon">Долгота</label><input class="form-control" type="text" name="lon" id="marker_lon" value="" disabled><br>
                </div>
            </div>
            <div class="form-group">
                <label for="submit">&nbsp;</label><input class="btn btn-lg btn-info" type="submit" name="submit" id="addmarker" value="Добавить">
            </div>
            <div id="response"></div>
        </form>
    </div>
    <!-- END CONTACT FORM -->
</div>
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">3. Выберите фотографии для привязки к этому месту</h3>


        <?php $this->widget('ext.EAjaxUpload.EAjaxUpload',
            array(
                'id'=>'uploadFile',
                'config'=>array(
                    'action'=>Yii::app()->createUrl('map/upload'),
                    'allowedExtensions'=>array('jpg', 'png', 'jpeg'),//array("jpg","jpeg","gif","exe","mov" and etc...
                    'sizeLimit'=>15*1024*1024,// maximum file size in bytes
                    'minSizeLimit'=>0.05*1024*1024,// minimum file size in bytes
                    'onComplete'=>"js:function(id, fileName, responseJSON){ idArray.push(responseJSON.id); }",
                )
            )); ?>


        <?php
        /*
        //выводим все фотки из портфолио
        if(!empty($album)){
            foreach($album as $item){ ?>
                <div class="col-lg-2 col-md-3 col-xs-6">
                    <a class="thumbnail">
                        <!--у каждой фотографии добавляем id равное ее id из БД-->
                        <img class="img-responsive for_check" id="<?php echo $item->id; ?>"
                             src="<?php echo Yii::app()->baseUrl.'/'.Thumbnail::getThumb($item->path); ?>" alt="">
                    </a>
                </div>
            <?php }
        }
        else{
            echo "Фотографии отсутствуют. <a href=".Yii::app()->urlManager->createUrl('cabinet/photos/create').">Загрузить фотографии</a>";
        }
        */
        ?>
    </div>

</div>



<script type="text/javascript">
    ymaps.ready(init);
    var myMap;
    var myPlacemark;
    var idArray = [];
    var idUser = <?php echo $id; ?>;
    var url = "<?php echo Yii::app()->urlManager->createUrl('map/getmap'); ?>/";

    function init() {

        //запрашиваем местоположение
        ymaps.geolocation.get().then(function (res) {
            var mapContainer = $('#map'),
                bounds = res.geoObjects.get(0).properties.get('boundedBy'),
            // Рассчитываем видимую область для текущей положения пользователя.
                mapState = ymaps.util.bounds.getCenterAndZoom(
                    bounds,
                    [mapContainer.width(), mapContainer.height()]
                );
            //создание карты, отцентрированной по местоположению пользователя
            createMap(mapState);
        }, function (e) {
            // Если местоположение невозможно получить, то просто создаем карту.
            createMap({
                center: [55.01, 82.94], //Новосибирск
                zoom: 12,
                controls: ['zoomControl','geolocationControl','searchControl']
            });
        });


        //функция создание карты с полученными данными о местоположении
        function createMap (state) {
            state.zoom = 12;
            //определяем контроллеры на карте
            state.controls = ['zoomControl','geolocationControl','searchControl'];
            //создаем карту в блоке div#map
            myMap = new ymaps.Map('map', state);

            //слушаем клики. По клику передаем географические координаты в форму
            myMap.events.add('click', function (e) {
                //читаем координаты
                var coords = e.get('coords');
                $('#marker_lat').val(coords[0]);
                $('#marker_lon').val(coords[1]);

                //если метка еще не создана - создаем
                //иначе, удаляем старую и создаем новую
                if(typeof(myPlacemark) == 'undefined')
                {
                    myPlacemark = new ymaps.Placemark([coords[0], coords[1]], { }, {
                        preset: 'islands#redDotIcon',
                        draggable: true
                    });
                    myMap.geoObjects.add(myPlacemark);
                }
                else
                {
                    myMap.geoObjects.remove(myPlacemark);
                    myPlacemark = new ymaps.Placemark([coords[0], coords[1]], { }, {
                        preset: 'islands#redDotIcon',
                        draggable: true
                    });
                    myMap.geoObjects.add(myPlacemark);
                }

                //слушаем событие dragend(перетаскивание метки). Переписываем координаты
                myPlacemark.events.add('dragend', function(e){
                    var coords = e.get('target').geometry.getCoordinates();
                    $('#marker_lat').val(coords[0]);
                    $('#marker_lon').val(coords[1]);
                });
            });

            //выводим все метки
            getPlacemarks(url,idUser);
        }


        //функция проверки заполнения всех полей
        function validate() {
            valid = true;
            //simple validation
            if(!$('#marker_lat').val()||!$('#marker_lon').val()||!$('#marker_balloontext').val()||!$('#marker_name').val()){
                valid = false;
            }
            return valid;
        }


        //поиск по значению в массиве
        //надо для поиска записанных id фоток, готовых к отправке
        function find(array, value) {
            if (array.indexOf) { // если метод существует
                return array.indexOf(value);
            }
            for(var i=0; i<array.length; i++) {
                if (array[i] === value) return i;
            }
            return -1;
        }


        //запрещаем отправку формы
        $('#marker_form').submit(false);


        //выбираем фоточки и добавляем id в массив
        $('a.thumbnail').click(function(){
            //узнаем id фотографии
            idx = $(this).find(':first-child').attr('id');
            //ищем индекс элемента массива со значенем id
            var index = find(idArray, idx);
            //TODO: проверять по индексу а не по классу
            if($(this).hasClass('added_photo')){
                $(this).removeClass('added_photo');
                //дополнительная проверка
                if(index != -1){
                    idArray.splice(index,1);
                }
            }
            else{
                $(this).addClass('added_photo');
                idArray.push(idx);
            }
        });


        //Показать все/мои метки
        $('#change_id').click(function(){
            if(idUser){
                idUser = null;
                getPlacemarks(url,idUser);
                $(this).text('Показать мои метки');
            }
            else{
                idUser = <?php echo $id; ?>;
                getPlacemarks(url,idUser);
                $(this).text('Показать все метки');
            }
        });



        //реагируем на нажатие кнопки отправки формы
        $('#addmarker').click(function(){

            if(validate()){
                //переводим js-массив в JSON формат
                photo_ids_json = JSON.stringify(idArray);

                $.ajax({
                    url: "<?php echo Yii::app()->urlManager->createUrl('map/addtomap'); ?>", //Адрес обработчика
                    type:     "POST", //Тип запроса
                    dataType: "html", //Тип данных
                    data: {
                        cam_id: <?php echo $id; ?>,
                        name: $('#marker_name').val(),
                        balloonText: $('#marker_balloontext').val(),
                        lat: $('#marker_lat').val(),
                        lon: $('#marker_lon').val(),
                        photo_ids: photo_ids_json
                    },
                    success: function(response) { //Если все нормально
                        $('#response').text('Место успешно добавлено в нашу базу.');

                        //сбрасываем форму
                        $('#marker_form').trigger('reset');

                        myMap.geoObjects.remove(myPlacemark);
                        getPlacemarks(idUser);
                        //нуллим переменную метки
                        myPlacemark = undefined;
                        idArray = [];
                    },
                    error: function(response) { //Если ошибка
                        $('#response').text('Ошибка.');
                    }
                });
            }
            else{
                $('#response').text('Заполните все поля!');
            }
        });
    }

</script>

protected/views/map/showPlaces.php
<script type="text/javascript">
    ymaps.ready(init);
    var myMap;
    var idUser = <?php if(isset($_GET['cam_id'])){echo Yii::app()->request->getQuery('cam_id');}
                        else{ echo 'undefined'; } ?>;
    var urlGetMap = "<?php echo Yii::app()->urlManager->createUrl('map/getmap') ?>/";
    var urlGetCamPhotos = "<?php echo Yii::app()->urlManager->createUrl('map/getCamPhotos')?>/";

    function init() {
        //запрашиваем местоположение
        ymaps.geolocation.get().then(function (res) {
            var mapContainer = $('#map'),
                bounds = res.geoObjects.get(0).properties.get('boundedBy'),
            // Рассчитываем видимую область для текущей положения пользователя.
                mapState = ymaps.util.bounds.getCenterAndZoom(
                    bounds,
                    [mapContainer.width(), mapContainer.height()]
                );
            //создание карты, отцентрированной по местоположению пользователя
            createMap(mapState);
        }, function (e) {
            // Если местоположение невозможно получить, то просто создаем карту.
            createMap({
                center: [55.01, 82.94], //Новосибирск
                zoom: 12,
                controls: ['zoomControl','geolocationControl','searchControl']
            });
        });


        //функция создание карты с полученными данными о местоположении
        function createMap (state) {
            state.zoom = 12;
            //определяем контроллеры на карте
            state.controls = ['zoomControl','geolocationControl','searchControl'];
            //создаем карту в блоке div#map
            myMap = new ymaps.Map('map', state);

            //выводим все метки
            getCamPlaces(urlGetMap, urlGetCamPhotos, idUser);
        }

        clusterer = new ymaps.Clusterer();
        clusterer.options.set({
            gridSize: 64
        });
        clusterer.add(myGeoObjects);
        myMap.geoObjects.add(clusterer);

        for (i = 0; i < json.markers.length; i++) {
            myPlacemark = new ymaps.Placemark([json.markers[i].lon, json.markers[i].lat], {

                balloonContentHeader: '<div style="color:#ff0303;font-weight:bold">'+json.markers[i].name+'</div>',
                balloonContentBody: '<strong>Адрес:</strong> '+json.markers[i].balloonText
            });
            myGeoObjects.push(myPlacemark);
        }

    }

</script>

<div class="row">
    <h2 class="page-header">Места фотографа <strong><?php echo Users::model()->findByPk(Yii::app()->request->getQuery('cam_id'))->fio; ?></strong></h2>

    <div class="col-lg-6">
        <div id="map" class="map"></div>
    </div>
    <div class="col-lg-6" id="showImg">

    </div>
</div>

<div id="blueimp-gallery-dialog" data-show="fade" data-hide="fade">
    <!-- The gallery widget  -->
    <div class="blueimp-gallery blueimp-gallery-carousel blueimp-gallery-controls">
        <div class="slides"></div>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="play-pause"></a>
    </div>
</div>

<br />
<br />