protected/models/Camerists.php
<?php

/**
 * This is the model class for table "camerists".
 *
 * The followings are the available columns in table 'camerists':
 * @property integer $user_id
 * @property string $rate
 *
 * The followings are the available model relations:
 * @property Albums[] $albums
 * @property Users $user
 * @property Comments[] $comments
 * @property Orders[] $orders
 * @property Rating[] $ratings
 * @property Schedule[] $schedules
 */
class Camerists extends CActiveRecord
{


    // If camerist - make album
    protected function afterSave()
    {
        if (parent::beforeSave())
        {
            $album = new Albums;
            $album->cam_id = $this->user_id;
            $album->name = 'Portfolio';
            $album->save();
            return true;
        }

        return false;
    }




	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'camerists';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('user_id', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('rate', 'length', 'max'=>2),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('user_id, rate', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'albums' => array(self::HAS_MANY, 'Albums', 'cam_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'comments' => array(self::HAS_MANY, 'Comments', 'cam_id'),
			'orders' => array(self::HAS_MANY, 'Orders', 'cam_id'),
			'ratings' => array(self::HAS_MANY, 'Rating', 'cam_id'),
			'schedules' => array(self::HAS_MANY, 'Schedule', 'cam_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'user_id' => 'User',
			'rate' => 'Rate',
		);
	}


    public function updateRating()
    {

        $getAverageRate = Yii::app()->db->createCommand(array(
                'select' => 'AVG(rate) as rt',
                'from' => 'rating',
                'where' => 'cam_id = :cam_id',
                'params' => array(':cam_id' => $this->user_id),
        ))->queryRow();

        if($getAverageRate['rt'] == '')
            $getAverageRate['rt'] = 0;
        $command = Yii::app()->db->createCommand();
        $command->update('camerists', array(
            'rate'=>$getAverageRate['rt'],
        ), 'user_id=:id', array(':id'=>$this->user_id));
    }

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('rate',$this->rate,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}


	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Camerists the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/CameristsController.php
<?php

class CameristsController extends Controller
{

    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    // List of all masters
	public function actionIndex()
	{
        // for pagination

        $criteria = new CDbCriteria();
        $criteria->condition = 'role = :role';
        $criteria->params = array(':role' => 'camerist');
        $count = Users::model()->count($criteria);
        $pages = new CPagination($count);
        $pages->pageSize = 15; // 15 per page
        $pages->applyLimit($criteria);

        $criteria->with = array('camerists');
        $criteria->together = true;




        $allCamerists = Users::model()->findAll($criteria);
        $this->render('index', array('camerists' => $allCamerists, 'pages' => $pages));
	}


    public function actionInfo(){




        $id = Yii::app()->request->getQuery('cam_id');
        $usr = Users::model()->findByPk($id);

        // For ghosts
        if(!isset($usr)){
            throw new CHttpException(404,'The specified post cannot be found.');
        }
        if($usr->role == 'user')
        {
            throw new CHttpException(404,'The specified post cannot be found.');
        }
        // Rate him

        $rating = new Rating;
        $cam = Camerists::model()->findByPk($id); // Save camerist for order
        if(isset($_POST['Rating'])){
            $rating->attributes = Yii::app()->request->getPost('Rating');
            $rating->cam_id = $id;
            $rating->user_id = Yii::app()->user->id;
            if($rating->save())
            {
                $cam->updateRating();
            }
        }


        $rate = $cam->rate;
        $album = Albums::model()->getAlbumId($id);
        $reviews = Comments::model()->getComments($id);
        $commenters = array();

        foreach($reviews as $rv)
            $commenters[] = Users::model()->findByPk($rv->user_id);
        $this->render('info', array(
            'camerist' => $usr,
            'commenters' => $commenters,
            'rate' => $rate,
            'album' => $album->getPhotos(),
            'reviews' => $reviews,
            'model' => $rating,  // for rate him at info page
        ));
    }
}

protected/controllers/CommentsController.php
<?php

class CommentsController extends Controller
{
    public function filters()
    {
        return array(
            'accessControl'
        );
    }


    public function accessRules()
    {
        return array(
            array('deny',
                'actions'=>array('add'),
                'users'=>array('?'),
            ),
            array('deny',
                'actions'=>array('add'),
                'roles'=>array('camerist'),
            ),
            array('allow',
                'actions'=>array('add', 'remove'),
                'roles'=>array('user'),
            ),

        );
    }


    public function actionRemove()
    {
        Comments::model()->remove($_GET['comm']);
        $this->redirect('index');
    }

	public function actionIndex()
	{
        $reviews = Comments::model()->findAllByAttributes(array('user_id' => Yii::app()->user->id));
        $camerists = array();
        // Just simple getting aims of comments
        foreach($reviews as $r)
            $camerists[] = Users::model()->findByPk($r->cam_id);

        $this->render('index', array('reviews' => $reviews, 'camerists' => $camerists));
	}

    public function actionAdd()
    {
        $comm = new Comments;

        // Leave comment

        if(isset($_POST['Comments']))
        {
            $comm->user_id = Yii::app()->user->id;
            $comm->cam_id = $_GET['cam_id'];
            $comm->attributes = Yii::app()->request->getPost('Comments');//$_POST['Comments'];
            if($comm->save())
                $this->render('congrats');
            else
                $this->render('add', array('model' => $comm));
        }
        else
        $this->render('add', array('model' => $comm));
    }


}

protected/controllers/OrdersController.php
<?php

class OrdersController extends Controller
{

    public function filters()
    {
        return array(
            'accessControl'
        );
    }



    public function accessRules()
    {
        return array(
            array('deny',
                'actions'=>array('accept', 'decline', 'finish', 'make'), // Guests can't rule the orders
                'users'=>array('?'),
            ),
            array('deny',
                'actions'=>array('make'),
                'roles'=>array('camerist'),
            ),
            array('allow',
                'actions'=>array('index', 'close'),
                'roles'=>array('user'),
            ),

        );
    }


	public function actionIndex()
	{

        // for pagination

        $criteria = new CDbCriteria();
        $criteria->condition = 'user_id = :u_id';
        $criteria->order = 'id desc';
        $criteria->params = array(':u_id' => Yii::app()->user->id);
        $count = Orders::model()->count($criteria);
        $pages = new CPagination($count);

        $pages->pageSize = 10; // 10 orders per page
        $pages->applyLimit($criteria);

        $myOrders = Orders::model()->findAll($criteria); //Orders::model()->findAllByAttributes(array('user_id' => Yii::app()->user->id));
		$camerists = array();
        foreach($myOrders as $o)
            $camerists[] = Users::model()->findByPk($o->cam_id);
        $this->render('index', array('orders' => $myOrders, 'camerists' => $camerists, 'pages' => $pages));
	}




    // TODO: bullshit, needs to refactor
    public function actionAccept()
    {

        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->accepted = true;
        $order->status = 'In progress';
        $order->save();
        $this->redirect('../cabinet/member/job');
    }

    public function actionDecline()
    {
        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->accepted = false;
        $order->status = 'Refused';

        $order->save();
        $this->redirect('../cabinet/member/job');
    }

    public function actionFinish()
    {
        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->status = 'Finished';

        $order->save();
        $this->redirect('../cabinet/member/job');
    }

    public function actionClose()
    {
        $order = Orders::model()->findByPk(Yii::app()->request->getQuery('order'));
        $order->scenario = 'status_change';
        $order->status = 'Closed';

        $order->save();
        $this->redirect('../orders/index');
    }


    public function actionMake()
    {
        $camId = Yii::app()->request->getQuery('cam_id');

        $orders = new Orders;
        $busy = Orders::model()->getBusy($camId);
        if(isset($_POST['Orders']))
        {
            $orders->attributes = $_POST['Orders'];
            $orders->cam_id = $camId;
            $orders->user_id = Yii::app()->user->id;

            if($orders->save())
                $this->render('congrats');
            else
                $this->render('make', array('model' => $orders, 'busy' => $busy));
        }
        else
            $this->render('make', array('model' => $orders, 'busy' => $busy));
    }

}

protected/controllers/RatingController.php
<?php

class RatingController extends Controller
{

    public function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function accessRules()
    {
        return array(
            array('deny',
                'actions'=>array('rate'),
                'users'=>array('?'),
            ),
            array('allow',
                'actions'=>array('rate', 'change'),
                'roles'=>array('user'),
            ),
            array('deny',
                'actions'=>array('rate'),
                'roles'=>array('camerist'),
            ),
        );
    }


    public function actionChange()
    {

        $criteria = new CDbCriteria;
        $criteria->select = 'id';
        $criteria->condition = 'cam_id = :c_id AND user_id = :u_id';
        $criteria->params = array(':c_id' => Yii::app()->request->getQuery('cam_id'), ':u_id'=>Yii::app()->user->id);
        Rating::model()->find($criteria)->delete();
        //Rating::model()->delete();
        $camId = Yii::app()->request->getQuery('cam_id');
        $cam = Camerists::model()->findByPk($camId); // Save camerist for order
        $cam->updateRating();
        $this->redirect(array('camerists/info', 'cam_id' => $camId));
    }


    public function actionIndex()
    {

        $rates = Rating::model()->findAllByAttributes(array('user_id' => Yii::app()->user->id));
        $camerists = array();
        // Just simple getting aims of comments
        foreach($rates as $r)
            $camerists[] = Users::model()->findByPk($r->cam_id);

        $this->render('index', array('rates' => $rates, 'camerists' => $camerists));
    }

    public function actionRate()
    {
        $rating = new Rating;

        $camId = Yii::app()->request->getQuery('cam_id');
        $cam = Camerists::model()->findByPk($camId); // Save camerist for order
        if(isset($_POST['Rating'])){
            $rating->attributes = Yii::app()->request->getPost('Rating');
            $rating->cam_id = $camId;
            $rating->user_id = Yii::app()->user->id;
            if($rating->save())
            {
                $this->render('congrats');
                $cam->updateRating();
            }
            else
                $this->render('rate', array('model'=>$rating));
        }
        else
            $this->render('rate', array('model'=>$rating));
    }

}

protected/views/camerists/index.php
<?php
/* @var $this CameristsController */
/* @var $camerist Users */

$this->breadcrumbs=array(
    'Camerists',
);
?>
<h2 class="page-header">Our photographers</h2>

<p>
    <?php foreach($camerists as $camerist): ?>
    <div class = "row user_list" >
        <div class="col-lg-2">
            <div class='avatar_list'>
                <?php
                echo CHtml::image(Yii::app()->baseUrl.'/'.Thumbnail::getThumb($camerist->avatar), 'Avatar');
                ?>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="fio">
                <h4><?php echo CHtml::link($camerist->fio, Yii::app()->createUrl('/camerists/info', array('cam_id' => $camerist->id))); ?></h4>
            </div>
            <?php echo 'Рейтинг: '.$camerist->camerists->rate; ?>
        </div>
        <div class="col-lg-8">
            <div class="photo_list">

            </div>
        </div>


    </div>
<br />
<?php endforeach; ?>

<?php
$this->widget('CLinkPager', array(
    'pages' => $pages,
));
?>

protected/views/camerists/info.php
<br />

<div class="row">

    <div class="col-lg-3">
        <div id='avatar' class="avatar">
            <?php
            echo CHtml::image(Yii::app()->baseUrl.'/'.$camerist->avatar, 'Avatar', array('style'=>'', 'width'=>'350px'));
            ?>
        </div>
        <div id="can">
            <?php if(Yii::app()->request->getQuery('cam_id')!=Yii::app()->user->id){?>
                <span class="btn btn-success">
                    <?php echo CHtml::link('Забронировать', Yii::app()->createUrl('orders/make', array('cam_id' => $camerist->id))); ?>
                </span>

                <span class="btn btn-danger">
                    <?php echo CHtml::link('Отзыв', Yii::app()->createUrl('/comments/add', array('cam_id' => $camerist->id))); ?>
                </span>

            <span class="btn btn-primary">
                <?php echo CHtml::link('Места фотографа', Yii::app()->createUrl('/map/showPlaces', array('cam_id' => $camerist->id))); ?>
            </span>
            <?php }else{ ?>
                <span class="btn btn-primary" style="width: 100%;">
                    <?php echo CHtml::link('Мои места', Yii::app()->createUrl('/map/showPlaces', array('cam_id' => $camerist->id))); ?>
                </span>
            <?php }?>
        </div>

        <?php if(Yii::app()->request->getQuery('cam_id')!=Yii::app()->user->id) {?>

        <div class="rate">

            <?php if(!Users::model()->isMadeRate($camerist->id)){ ?>
                <?php $form = $this->beginWidget('CActiveForm'); ?>

                <?php echo $form->errorSummary($model); ?>

                <div class="compactRadioGroup">
                    <p>
                        <?php
                        echo $form->radioButtonList($model,'rate',array('1'=>'1', '2'=>'2', '3'=>'3', '4'=>'4', '5'=> '5'), array('separator' => ''));
                        ?>

                        <?php echo CHtml::submitButton('Rate', array('class' => 'btn btn-default')); ?>
                    </p>
                </div>


                <?php $this->endWidget(); ?>


            <?php }
            else{
                echo 'Моя оценка: ' . Users::model()->getRate($camerist->id);
                echo "&nbsp;&nbsp;";
                echo '<span class="btn">';
                echo CHtml::link('Я передумал', Yii::app()->createUrl('rating/change', array('cam_id' => $camerist->id)), array('class' => 'btn btn-default'));
                echo '<span>';
            }
            echo "</div>";
            }
            ?>

            <!-- rate-->

        </div>
        <div class="col-lg-4">
            <h2><?php echo $camerist->fio; ?></h2>
            <div id="rating">
                <?php echo 'Рейтинг: <strong> ' . $rate .'</strong>'; ?>
            </div>
            <div id="contacts">
                <?php echo 'Телефон: <strong>' . $camerist->tel .'</strong>'; ?>
                <br />
                <?php echo 'Электропочта: <strong>' . $camerist->email .'</strong>'; ?>
            </div>
            <div id='about'>
                <strong>Обо мне:</strong><br />
                <?php echo $camerist->about; ?>
            </div>

        </div>
        <div class="col-lg-5">
            <div id="map" class="map"></div>
        </div>
    </div>









    <div class="row">
        <div id='gallery'>
            <h3 class="page-header">Портфолио</h3>
            <?php
            if(!$album)
                echo 'Этот фотограф еще не загрузил ни одной фотографии.';
            else {
                ?>

                <div id="links">
                    <?php foreach($album as $item): ?>
                        <?php if($item->published): ?>

                            <a href = "<?php echo  Yii::app()->baseUrl.'/'.$item->path; ?>" data-dialog>
                                <div>
                                    <?php echo CHtml::image(Yii::app()->baseUrl.'/'.Thumbnail::getThumb($item->path), 'Portfolio item'); ?>
                                </div>
                            </a>

                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>

            <?php } ?>
            <div id="blueimp-gallery-dialog" data-show="fade" data-hide="fade">
                <!-- The gallery widget  -->
                <div class="blueimp-gallery blueimp-gallery-carousel blueimp-gallery-controls">
                    <div class="slides"></div>
                    <a class="prev">‹</a>
                    <a class="next">›</a>
                    <a class="play-pause"></a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div id="reviews">
            <h4>Отзывы от благодарных клиентов</h4>
            <?php
            if(!$reviews)
                echo 'Отзывов пока нету :(';
            foreach($reviews as $i => $r)
            {
                ?>
                <div class="review">
                    <?php if(isset($r)) { ?>
                        <strong><?php echo $commenters[$i]->fio; ?></strong>
                        <p class="text">
                            <?php echo $r->message; ?>
                        </p>

                        <div class="date"><?php echo $r->created_at ?></div>
                    <?php } ?>
                </div>
            <?php
            }
            ?>
        </div>
    </div>
    <br />
    <br />
</div>



<script>

    ymaps.ready(init);
    var myMap;
    var myLocation;
    var url = "<?php echo Yii::app()->urlManager->createUrl('map/getcamlocation'); ?>/";

    function init() {
        myId = <?php echo Yii::app()->request->getQuery('cam_id'); ?>

            myMap = new ymaps.Map('map', {
                center: [55.02, 82.93], // Новосибирск
                zoom: 13,
                controls: ['zoomControl','geolocationControl','searchControl']
            });

        //делаем запрос на местоположение пользователя
        $.getJSON(url+myId,
            function(json){

                //если координаты есть, то добавляем метку на карту и цнтрируемся по ней
                if(json.marker[0].lat!=null&& json.marker[0].lon!=null){
                    myLocation = new ymaps.Placemark([json.marker[0].lat, json.marker[0].lon],
                        {
                            balloonContentBody: 'Фотограф находится здесь)'
                        }, {
                            // Опции
                            preset: 'islands#greenDotIcon'
                        });
                    myMap.geoObjects.add(myLocation);
                    myMap.setCenter([json.marker[0].lat, json.marker[0].lon]);
                }
            }
        );

        //создаем карту и центрируем ее на Новосибирск

    }


</script>